---
# Handlers for security role
- name: Reload nftables
  become: yes
  ansible.builtin.systemd_service: { name: nftables.service, state: reloaded }
  listen: "Reload nftables"
  when: firewall_choice == 'nftables'
- name: Restart ufw
  become: yes
  ansible.builtin.systemd_service: { name: ufw.service, state: restarted }
  listen: "Restart ufw"
  when: firewall_choice == 'ufw'
